#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


current_branch=$(git rev-parse --abbrev-ref HEAD)

if [[ $current_branch == "main" ]]; then
  echo "\033[1;31m COMMIT REJECTED FOR MAIN BRANCH"
  echo "\033[;37m Please create a new branch with:"
  echo "\033[32m git checkout -b name-of-new-branch"
  echo "\033[37m Then proceed to follow the team pull request procedures."
  exit 1;
else
  echo "Committing to " $current_branch
fi

npm run format
npm run lint

