name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Lint
        run: npx next lint

      # - name: Run linters
      #   uses: wearerequired/lint-action@v2
      #   with:
      #     eslint: true
      #     prettier: true
      #     auto_fix: false # This can end up causing annoying git conflicts if the devs aren't running prettier locally. Probably should just fail CI and force them to run prettier locally to fix it. TODO: add documentation about how to set up prettier to run on saving a file in VSCode
